<service id="9600000663502406" serviceName="SBSERVICE06" serviceType="N" active="1" channelId="001" batch="0" batchType="" ortam="CB"><description>This name can be used.</description><hasTableLock>0</hasTableLock><methodName>sendTest</methodName><scClassName>cb.smg.senoldeneme.TestDeneme</scClassName><target>0</target><ttype>0</ttype><visible>1</visible><platform>1</platform><componentId>9990000308707615</componentId><componentCmsOid>9990000308707615</componentCmsOid><lastUpdated>1721809448504</lastUpdated></service>